// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cc_errors

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE5cbebb2DecodeGithubComSolarLabRUFastpayGoCommonsCcErrors(in *jlexer.Lexer, out *JsonSerializableErr) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = int(in.Int())
		case "message":
			out.Message = string(in.String())
		case "data":
			if m, ok := out.Details.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Details.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Details = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5cbebb2EncodeGithubComSolarLabRUFastpayGoCommonsCcErrors(out *jwriter.Writer, in JsonSerializableErr) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if m, ok := in.Details.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Details.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Details))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v JsonSerializableErr) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE5cbebb2EncodeGithubComSolarLabRUFastpayGoCommonsCcErrors(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v JsonSerializableErr) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5cbebb2EncodeGithubComSolarLabRUFastpayGoCommonsCcErrors(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *JsonSerializableErr) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE5cbebb2DecodeGithubComSolarLabRUFastpayGoCommonsCcErrors(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *JsonSerializableErr) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5cbebb2DecodeGithubComSolarLabRUFastpayGoCommonsCcErrors(l, v)
}
func easyjsonE5cbebb2DecodeGithubComSolarLabRUFastpayGoCommonsCcErrors1(in *jlexer.Lexer, out *Error) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Code":
			out.Code = int(in.Int())
		case "Message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5cbebb2EncodeGithubComSolarLabRUFastpayGoCommonsCcErrors1(out *jwriter.Writer, in Error) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"Message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Error) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE5cbebb2EncodeGithubComSolarLabRUFastpayGoCommonsCcErrors1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Error) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5cbebb2EncodeGithubComSolarLabRUFastpayGoCommonsCcErrors1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Error) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE5cbebb2DecodeGithubComSolarLabRUFastpayGoCommonsCcErrors1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Error) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5cbebb2DecodeGithubComSolarLabRUFastpayGoCommonsCcErrors1(l, v)
}
func easyjsonE5cbebb2DecodeGithubComSolarLabRUFastpayGoCommonsCcErrors2(in *jlexer.Lexer, out *BaseError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = int(in.Int())
		case "message":
			out.Message = string(in.String())
		case "data":
			out.Data = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5cbebb2EncodeGithubComSolarLabRUFastpayGoCommonsCcErrors2(out *jwriter.Writer, in BaseError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BaseError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE5cbebb2EncodeGithubComSolarLabRUFastpayGoCommonsCcErrors2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BaseError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5cbebb2EncodeGithubComSolarLabRUFastpayGoCommonsCcErrors2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BaseError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE5cbebb2DecodeGithubComSolarLabRUFastpayGoCommonsCcErrors2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BaseError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5cbebb2DecodeGithubComSolarLabRUFastpayGoCommonsCcErrors2(l, v)
}
