// Generated by: gen
// TypeWriter: set
// Directive: +gen on AddressOfAccount

package models

// Set is a modification of https://github.com/deckarep/golang-set
// The MIT License (MIT)
// Copyright (c) 2013 Ralph Caraveo (deckarep@gmail.com)

// AddressOfAccountSet is the primary type that represents a set
type AddressOfAccountSet map[AddressOfAccount]struct{}

// NewAddressOfAccountSet creates and returns a reference to an empty set.
func NewAddressOfAccountSet(a ...AddressOfAccount) AddressOfAccountSet {
	s := make(AddressOfAccountSet)
	for _, i := range a {
		s.Add(i)
	}
	return s
}

// ToSlice returns the elements of the current set as a slice
func (set AddressOfAccountSet) ToSlice() []AddressOfAccount {
	var s []AddressOfAccount
	for v := range set {
		s = append(s, v)
	}
	return s
}

// Add adds an item to the current set if it doesn't already exist in the set.
func (set AddressOfAccountSet) Add(i AddressOfAccount) bool {
	_, found := set[i]
	set[i] = struct{}{}
	return !found //False if it existed already
}

// Contains determines if a given item is already in the set.
func (set AddressOfAccountSet) Contains(i AddressOfAccount) bool {
	_, found := set[i]
	return found
}

// ContainsAll determines if the given items are all in the set
func (set AddressOfAccountSet) ContainsAll(i ...AddressOfAccount) bool {
	for _, v := range i {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

// IsSubset determines if every item in the other set is in this set.
func (set AddressOfAccountSet) IsSubset(other AddressOfAccountSet) bool {
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// IsSuperset determines if every item of this set is in the other set.
func (set AddressOfAccountSet) IsSuperset(other AddressOfAccountSet) bool {
	return other.IsSubset(set)
}

// Union returns a new set with all items in both sets.
func (set AddressOfAccountSet) Union(other AddressOfAccountSet) AddressOfAccountSet {
	unionedSet := NewAddressOfAccountSet()

	for elem := range set {
		unionedSet.Add(elem)
	}
	for elem := range other {
		unionedSet.Add(elem)
	}
	return unionedSet
}

// Intersect returns a new set with items that exist only in both sets.
func (set AddressOfAccountSet) Intersect(other AddressOfAccountSet) AddressOfAccountSet {
	intersection := NewAddressOfAccountSet()
	// loop over smaller set
	if set.Cardinality() < other.Cardinality() {
		for elem := range set {
			if other.Contains(elem) {
				intersection.Add(elem)
			}
		}
	} else {
		for elem := range other {
			if set.Contains(elem) {
				intersection.Add(elem)
			}
		}
	}
	return intersection
}

// Difference returns a new set with items in the current set but not in the other set
func (set AddressOfAccountSet) Difference(other AddressOfAccountSet) AddressOfAccountSet {
	differencedSet := NewAddressOfAccountSet()
	for elem := range set {
		if !other.Contains(elem) {
			differencedSet.Add(elem)
		}
	}
	return differencedSet
}

// SymmetricDifference returns a new set with items in the current set or the other set but not in both.
func (set AddressOfAccountSet) SymmetricDifference(other AddressOfAccountSet) AddressOfAccountSet {
	aDiff := set.Difference(other)
	bDiff := other.Difference(set)
	return aDiff.Union(bDiff)
}

// Clear clears the entire set to be the empty set.
func (set *AddressOfAccountSet) Clear() {
	*set = make(AddressOfAccountSet)
}

// Remove allows the removal of a single item in the set.
func (set AddressOfAccountSet) Remove(i AddressOfAccount) {
	delete(set, i)
}

// Cardinality returns how many items are currently in the set.
func (set AddressOfAccountSet) Cardinality() int {
	return len(set)
}

// Iter returns a channel of type AddressOfAccount that you can range over.
func (set AddressOfAccountSet) Iter() <-chan AddressOfAccount {
	ch := make(chan AddressOfAccount)
	go func() {
		for elem := range set {
			ch <- elem
		}
		close(ch)
	}()

	return ch
}

// Equal determines if two sets are equal to each other.
// If they both are the same size and have the same items they are considered equal.
// Order of items is not relevent for sets to be equal.
func (set AddressOfAccountSet) Equal(other AddressOfAccountSet) bool {
	if set.Cardinality() != other.Cardinality() {
		return false
	}
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Clone returns a clone of the set.
// Does NOT clone the underlying elements.
func (set AddressOfAccountSet) Clone() AddressOfAccountSet {
	clonedSet := NewAddressOfAccountSet()
	for elem := range set {
		clonedSet.Add(elem)
	}
	return clonedSet
}
