// Generated by: gen
// TypeWriter: set
// Directive: +gen on *CurrencyExchangeContract

package models

// Set is a modification of https://github.com/deckarep/golang-set
// The MIT License (MIT)
// Copyright (c) 2013 Ralph Caraveo (deckarep@gmail.com)

// CurrencyExchangeContractSet is the primary type that represents a set
type CurrencyExchangeContractSet map[*CurrencyExchangeContract]struct{}

// NewCurrencyExchangeContractSet creates and returns a reference to an empty set.
func NewCurrencyExchangeContractSet(a ...*CurrencyExchangeContract) CurrencyExchangeContractSet {
	s := make(CurrencyExchangeContractSet)
	for _, i := range a {
		s.Add(i)
	}
	return s
}

// ToSlice returns the elements of the current set as a slice
func (set CurrencyExchangeContractSet) ToSlice() []*CurrencyExchangeContract {
	var s []*CurrencyExchangeContract
	for v := range set {
		s = append(s, v)
	}
	return s
}

// Add adds an item to the current set if it doesn't already exist in the set.
func (set CurrencyExchangeContractSet) Add(i *CurrencyExchangeContract) bool {
	_, found := set[i]
	set[i] = struct{}{}
	return !found //False if it existed already
}

// Contains determines if a given item is already in the set.
func (set CurrencyExchangeContractSet) Contains(i *CurrencyExchangeContract) bool {
	_, found := set[i]
	return found
}

// ContainsAll determines if the given items are all in the set
func (set CurrencyExchangeContractSet) ContainsAll(i ...*CurrencyExchangeContract) bool {
	for _, v := range i {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

// IsSubset determines if every item in the other set is in this set.
func (set CurrencyExchangeContractSet) IsSubset(other CurrencyExchangeContractSet) bool {
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// IsSuperset determines if every item of this set is in the other set.
func (set CurrencyExchangeContractSet) IsSuperset(other CurrencyExchangeContractSet) bool {
	return other.IsSubset(set)
}

// Union returns a new set with all items in both sets.
func (set CurrencyExchangeContractSet) Union(other CurrencyExchangeContractSet) CurrencyExchangeContractSet {
	unionedSet := NewCurrencyExchangeContractSet()

	for elem := range set {
		unionedSet.Add(elem)
	}
	for elem := range other {
		unionedSet.Add(elem)
	}
	return unionedSet
}

// Intersect returns a new set with items that exist only in both sets.
func (set CurrencyExchangeContractSet) Intersect(other CurrencyExchangeContractSet) CurrencyExchangeContractSet {
	intersection := NewCurrencyExchangeContractSet()
	// loop over smaller set
	if set.Cardinality() < other.Cardinality() {
		for elem := range set {
			if other.Contains(elem) {
				intersection.Add(elem)
			}
		}
	} else {
		for elem := range other {
			if set.Contains(elem) {
				intersection.Add(elem)
			}
		}
	}
	return intersection
}

// Difference returns a new set with items in the current set but not in the other set
func (set CurrencyExchangeContractSet) Difference(other CurrencyExchangeContractSet) CurrencyExchangeContractSet {
	differencedSet := NewCurrencyExchangeContractSet()
	for elem := range set {
		if !other.Contains(elem) {
			differencedSet.Add(elem)
		}
	}
	return differencedSet
}

// SymmetricDifference returns a new set with items in the current set or the other set but not in both.
func (set CurrencyExchangeContractSet) SymmetricDifference(other CurrencyExchangeContractSet) CurrencyExchangeContractSet {
	aDiff := set.Difference(other)
	bDiff := other.Difference(set)
	return aDiff.Union(bDiff)
}

// Clear clears the entire set to be the empty set.
func (set *CurrencyExchangeContractSet) Clear() {
	*set = make(CurrencyExchangeContractSet)
}

// Remove allows the removal of a single item in the set.
func (set CurrencyExchangeContractSet) Remove(i *CurrencyExchangeContract) {
	delete(set, i)
}

// Cardinality returns how many items are currently in the set.
func (set CurrencyExchangeContractSet) Cardinality() int {
	return len(set)
}

// Iter returns a channel of type *CurrencyExchangeContract that you can range over.
func (set CurrencyExchangeContractSet) Iter() <-chan *CurrencyExchangeContract {
	ch := make(chan *CurrencyExchangeContract)
	go func() {
		for elem := range set {
			ch <- elem
		}
		close(ch)
	}()

	return ch
}

// Equal determines if two sets are equal to each other.
// If they both are the same size and have the same items they are considered equal.
// Order of items is not relevent for sets to be equal.
func (set CurrencyExchangeContractSet) Equal(other CurrencyExchangeContractSet) bool {
	if set.Cardinality() != other.Cardinality() {
		return false
	}
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Clone returns a clone of the set.
// Does NOT clone the underlying elements.
func (set CurrencyExchangeContractSet) Clone() CurrencyExchangeContractSet {
	clonedSet := NewCurrencyExchangeContractSet()
	for elem := range set {
		clonedSet.Add(elem)
	}
	return clonedSet
}
