// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package models

import (
	currencyexchangecontracttypeenum "github.com/SolarLabRU/fastpay-go-commons/enums/currency-exchange-contract-type-enum"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Account) DeepCopyInto(out *Account) {
	*out = *in
	if in.AvailableContractTypes != nil {
		in, out := &in.AvailableContractTypes, &out.AvailableContractTypes
		*out = make([]currencyexchangecontracttypeenum.CurrencyExchangeContractType, len(*in))
		copy(*out, *in)
	}
	if in.Identifiers != nil {
		in, out := &in.Identifiers, &out.Identifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Account.
func (in *Account) DeepCopy() *Account {
	if in == nil {
		return nil
	}
	out := new(Account)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmountOfBank) DeepCopyInto(out *AmountOfBank) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmountOfBank.
func (in *AmountOfBank) DeepCopy() *AmountOfBank {
	if in == nil {
		return nil
	}
	out := new(AmountOfBank)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrencyContractRoutingItem) DeepCopyInto(out *CurrencyContractRoutingItem) {
	*out = *in
	out.CurrencyExchangeContract = in.CurrencyExchangeContract
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrencyContractRoutingItem.
func (in *CurrencyContractRoutingItem) DeepCopy() *CurrencyContractRoutingItem {
	if in == nil {
		return nil
	}
	out := new(CurrencyContractRoutingItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrencyExchangeContract) DeepCopyInto(out *CurrencyExchangeContract) {
	*out = *in
	out.CurrencyExchangeContractMutable = in.CurrencyExchangeContractMutable
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrencyExchangeContract.
func (in *CurrencyExchangeContract) DeepCopy() *CurrencyExchangeContract {
	if in == nil {
		return nil
	}
	out := new(CurrencyExchangeContract)
	in.DeepCopyInto(out)
	return out
}
